services:
  server:
    container_name: server
    volumes:
      - "D:/IT/DutyachiySvit/frontend/src/static/products:/app/static/products"
      - "D:/IT/DutyachiySvit/backend/internal/email_sender/template_html:/app/internal/email_sender/template_html"
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_healthy
    hostname: products
    env_file:
      - ./.env
    ports:
      - "$PORT:$PORT"

  mongo:
    image: mongo:latest
    container_name: server_db
    restart: unless-stopped
    tty: true
    ports:
      - "$MONGODB_PORT:$MONGODB_PORT"
    volumes:
      - mongo_data:/data/db
    env_file:
      - ./.env
    healthcheck:
      test: ["CMD", "echo", "MongoDB is running"]
      interval: 10s
      timeout: 5s
      retries: 10

  redis:
    image: redis:latest
    container_name: redis_db
    restart: unless-stopped
    ports:
      - "$REDISDB_PORT:$REDISDB_PORT"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  mongo_data:
  redis_data:
