services:
  server:
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      mongo:
        condition: service_healthy
    hostname: products
    env_file:
      - ./.env
    ports:
      - "8000:8000"

  mongo:
    image: mongo:latest
    container_name: server_db
    restart: unless-stopped
    tty: true
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    env_file:
      - ./.env
    healthcheck:
      test: ["CMD", "echo", "MongoDB is running"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  mongo_data: